#
# © 2024-present https://github.com/cengiz-pz
#

[versions]
compileSdk = "35"
minSdk = "24"
buildTools = "35.0.0"
appcompat = "1.7.1"
playReview = "2.0.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
play-review = { module = "com.google.android.play:review", version.ref = "playReview" }

[plugins]
android-library = { id = "com.android.library", version = "8.6.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.2.0" }
undercouch-download = { id = "de.undercouch.download", version = "5.6.0" }
